# Generated by Django 4.0.5 on 2022-06-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='buyer',
        ),
    ]
